[package]
name = "day1"
version = "0.1.0"
authors = ["Peter Simon <simon.peter.90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
itertools = "0.7.8"
